// angular import
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';

// project import
import { UserService } from 'src/app/core/services/user.service';

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.scss']
})
export class SignupComponent {
  private userService = inject(UserService);
  private router = inject(Router);

  email = '';
  password = '';
  confirmPassword = '';
  loading = false;
  error: string | null = null;
  success: string | null = null;

  onSubmit(): void {
    this.error = null;
    this.success = null;

    // Validation
    if (!this.email || !this.password || !this.confirmPassword) {
      this.error = 'Please fill in all fields';
      return;
    }

    if (this.password !== this.confirmPassword) {
      this.error = 'Passwords do not match';
      return;
    }

    if (this.password.length < 6) {
      this.error = 'Password must be at least 6 characters';
      return;
    }

    this.loading = true;

    // Create user via API
    const newUser = {
      id: '', // Will be generated by backend
      email: this.email,
      isAdmin: false,
      isActive: true,
      note: 'User created via signup'
    };

    this.userService.createUser({ user: newUser, password: this.password }).subscribe({
      next: (response) => {
        console.log('✅ User created successfully:', response.id);
        this.loading = false;
        this.success = 'Account created successfully! Redirecting to login...';
        
        // Redirect to login after 2 seconds
        setTimeout(() => {
          this.router.navigate(['/login']);
        }, 2000);
      },
      error: (err) => {
        this.error = 'Failed to create account: ' + (err.error?.message || err.message);
        this.loading = false;
        console.error('Error creating user:', err);
      }
    });
  }
}

